// <auto-generated />
using System;
using GroupProject_POS_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupProject_POS_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupProject_POS_System.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CreatedAt = new DateTime(2024, 11, 30, 14, 14, 55, 621, DateTimeKind.Local).AddTicks(425),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            CustomerID = 2,
                            CreatedAt = new DateTime(2024, 11, 30, 14, 14, 55, 623, DateTimeKind.Local).AddTicks(4809),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "987-654-3210"
                        });
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Email = "alice.kosh@example.com",
                            FirstName = "Alice",
                            LastName = "Kosh",
                            PasswordHash = "$2a$11$2JPpX8hjE7K4u8W.YlMSF.j7uK/8qdX0WIQ3ppVMhb7e1V4I1i..u",
                            Role = "Staff"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Email = "bob.mash@example.com",
                            FirstName = "Bob",
                            LastName = "Mash",
                            PasswordHash = "$2a$11$17VtfmMvQRXHlHCeAmgV9u0p6vI1fT1zt42ZRxG3V858h80IDGRtS",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            Category = "Haircut",
                            Price = 25.00m,
                            ServiceName = "Men's Haircut"
                        },
                        new
                        {
                            ServiceID = 2,
                            Category = "Haircut",
                            Price = 35.00m,
                            ServiceName = "Women's Haircut"
                        },
                        new
                        {
                            ServiceID = 3,
                            Category = "Haircut",
                            Price = 15.00m,
                            ServiceName = "Men's Beard Trim"
                        },
                        new
                        {
                            ServiceID = 4,
                            Category = "Manicure",
                            Price = 30.00m,
                            ServiceName = "Manicure"
                        },
                        new
                        {
                            ServiceID = 5,
                            Category = "Pedicure",
                            Price = 40.00m,
                            ServiceName = "Pedicure"
                        },
                        new
                        {
                            ServiceID = 6,
                            Category = "Manicure",
                            Price = 40.00m,
                            ServiceName = "Gel Manicure"
                        },
                        new
                        {
                            ServiceID = 7,
                            Category = "Pedicure",
                            Price = 45.00m,
                            ServiceName = "French Pedicure"
                        });
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = 1,
                            CustomerID = 1,
                            EmployeeID = 1,
                            PaymentType = "Cash",
                            TotalAmount = 60.00m,
                            TransactionDate = new DateTime(2024, 11, 30, 14, 14, 55, 623, DateTimeKind.Local).AddTicks(6569)
                        });
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionDetailID"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.HasKey("TransactionDetailID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("TransactionID");

                    b.ToTable("TransactionDetail");

                    b.HasData(
                        new
                        {
                            TransactionDetailID = 1,
                            Quantity = 1,
                            ServiceID = 1,
                            Subtotal = 25.00m,
                            TransactionID = 1
                        },
                        new
                        {
                            TransactionDetailID = 2,
                            Quantity = 1,
                            ServiceID = 2,
                            Subtotal = 35.00m,
                            TransactionID = 1
                        });
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Transaction", b =>
                {
                    b.HasOne("GroupProject_POS_System.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerID");

                    b.HasOne("GroupProject_POS_System.Models.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.TransactionDetail", b =>
                {
                    b.HasOne("GroupProject_POS_System.Models.Service", "Service")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupProject_POS_System.Models.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Employee", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Service", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GroupProject_POS_System.Models.Transaction", b =>
                {
                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
